name: GitHub Actions
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install
        with:
          MOLLIE_CONFIG: ${{ secrets.MOLLIE_CONFIG_JSON }}

      - name: Build
        run: npm start

      - name: Move node modules to build folder
        run: mv node_modules build/

      - name: Zip contents
        run: (cd build && zip -r ../function.zip .)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        env:
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: get-mollie-payment-methods-lambda
          MOLLIE_TEST_API_KEY: ${{ secrets.MOLLIE_TEST_API_KEY }}
          zip_file: function.zip
